import type { CustomizationFieldDef } from "@/lib/customization-types";

const BY_SUBCATEGORY: Record<string, CustomizationFieldDef[]> = {
  "Chocolate Wrappers": [
    {
      key: "design_file",
      type: "image",
      label: "Your design or photo",
      required: true,
      hint: "We accept JPG, PNG. If you have a ready design, upload it. Otherwise describe what you want in the notes.",
    },
    {
      key: "name_text",
      type: "text",
      label: "Name or text to print",
      required: false,
      maxChars: 40,
    },
    {
      key: "occasion",
      type: "select",
      label: "Occasion",
      required: true,
      options: ["Birthday", "Wedding", "Corporate", "Baby Shower", "Anniversary"],
    },
    {
      key: "notes",
      type: "textarea",
      label: "Additional instructions",
      required: false,
      maxChars: 200,
    },
  ],
  "Custom Stickers & Labels": [
    {
      key: "logo_file",
      type: "image",
      label: "Your logo or artwork",
      required: true,
      hint: "Upload high resolution PNG with transparent background if possible",
    },
    {
      key: "text_line1",
      type: "text",
      label: "Line 1 text",
      required: false,
      maxChars: 40,
    },
    {
      key: "text_line2",
      type: "text",
      label: "Line 2 text (optional)",
      required: false,
      maxChars: 40,
    },
    {
      key: "notes",
      type: "textarea",
      label: "Design instructions",
      required: false,
      maxChars: 200,
    },
  ],
  "Branded Tissue Paper": [
    {
      key: "logo_file",
      type: "image",
      label: "Your logo",
      required: true,
    },
    {
      key: "brand_name",
      type: "text",
      label: "Brand name",
      required: true,
      maxChars: 50,
    },
    {
      key: "notes",
      type: "textarea",
      label: "Design instructions",
      required: false,
      maxChars: 200,
    },
  ],
  "Custom Bottle Labels": [
    {
      key: "photo",
      type: "image",
      label: "Photo (optional)",
      required: false,
      hint: "Leave blank if text-only design",
    },
    {
      key: "name_text",
      type: "text",
      label: "Names or event title",
      required: true,
      maxChars: 50,
    },
    {
      key: "date",
      type: "text",
      label: "Event date",
      required: false,
      hint: "e.g. 14 Feb 2026",
    },
    {
      key: "notes",
      type: "textarea",
      label: "Design notes",
      required: false,
      maxChars: 200,
    },
  ],
  "Tear-off Calendars": [
    {
      key: "cover_photo",
      type: "image",
      label: "Cover photo",
      required: true,
    },
    {
      key: "name",
      type: "text",
      label: "Name on cover",
      required: false,
      maxChars: 40,
    },
    {
      key: "year",
      type: "text",
      label: "Year",
      required: true,
      hint: "e.g. 2026",
    },
    {
      key: "notes",
      type: "textarea",
      label: "Special dates to mark",
      required: false,
      maxChars: 300,
    },
  ],
  "Photo Keychains": [
    {
      key: "photo",
      type: "image",
      label: "Your photo",
      required: true,
      hint: "Clear face photo works best. Square crop recommended.",
    },
    {
      key: "name",
      type: "text",
      label: "Name",
      required: false,
      maxChars: 25,
    },
    {
      key: "spotify_url",
      type: "url",
      label: "Spotify song link",
      required: false,
      hint: "Open Spotify app → tap the song → Share → Copy link. Paste here.",
    },
    {
      key: "sub_text",
      type: "text",
      label: "Subtitle text",
      required: false,
      hint: "e.g. 'Our song' or a date",
      maxChars: 30,
    },
  ],
  "Desk Plaques": [
    {
      key: "photo",
      type: "image",
      label: "Photo (optional)",
      required: false,
    },
    {
      key: "name",
      type: "text",
      label: "Name",
      required: true,
      maxChars: 50,
    },
    {
      key: "title",
      type: "text",
      label: "Designation/title",
      required: false,
      maxChars: 50,
    },
    {
      key: "quote",
      type: "textarea",
      label: "Quote or message",
      required: false,
      maxChars: 100,
    },
  ],
  "Cake Toppers": [
    {
      key: "name",
      type: "text",
      label: "Name to cut",
      required: true,
      maxChars: 20,
      hint: "Shorter names look better",
    },
    {
      key: "age",
      type: "text",
      label: "Age/number (optional)",
      required: false,
      maxChars: 3,
    },
    {
      key: "sub_text",
      type: "text",
      label: "Sub text (optional)",
      required: false,
      maxChars: 20,
      hint: "e.g. 'Happy Birthday'",
    },
  ],
  "Custom Bag Tags": [
    {
      key: "photo",
      type: "image",
      label: "Photo (optional)",
      required: false,
    },
    {
      key: "name",
      type: "text",
      label: "Name",
      required: true,
      maxChars: 30,
    },
    {
      key: "phone",
      type: "text",
      label: "Phone number (optional)",
      required: false,
      maxChars: 15,
      hint: "Useful for lost bag recovery",
    },
  ],
  "Acrylic Name Plates": [
    {
      key: "name",
      type: "text",
      label: "Name",
      required: true,
      maxChars: 40,
    },
    {
      key: "designation",
      type: "text",
      label: "Designation/title",
      required: false,
      maxChars: 50,
    },
    {
      key: "logo_file",
      type: "image",
      label: "Logo (optional)",
      required: false,
    },
  ],
  "Acrylic Fridge Magnets": [
    {
      key: "photo",
      type: "image",
      label: "Your photo",
      required: true,
      hint: "Clear photo. Group photos work great.",
    },
    {
      key: "name",
      type: "text",
      label: "Name or caption",
      required: false,
      maxChars: 30,
    },
  ],
  "Journals & Notebooks": [
    {
      key: "name",
      type: "text",
      label: "Name to engrave/print",
      required: true,
      maxChars: 30,
    },
    {
      key: "monogram",
      type: "text",
      label: "Monogram (optional)",
      required: false,
      maxChars: 3,
      hint: "e.g. 'ARS' for initials",
    },
    {
      key: "cover_art",
      type: "image",
      label: "Custom cover image (optional)",
      required: false,
    },
  ],
  "Custom Bookmarks": [
    {
      key: "photo",
      type: "image",
      label: "Photo (optional)",
      required: false,
    },
    {
      key: "quote",
      type: "textarea",
      label: "Inspirational quote",
      required: false,
      maxChars: 120,
    },
    {
      key: "name",
      type: "text",
      label: "Name",
      required: false,
      maxChars: 25,
    },
  ],
  "Desk Organizers": [
    {
      key: "name",
      type: "text",
      label: "Name to engrave",
      required: true,
      maxChars: 30,
    },
    {
      key: "logo_file",
      type: "image",
      label: "Logo (optional)",
      required: false,
    },
  ],
  Mousepads: [
    {
      key: "design_file",
      type: "image",
      label: "Your photo or design",
      required: true,
      hint: "Upload your family photo, artwork, or design file. JPG or PNG, minimum 1500px wide.",
    },
    {
      key: "name",
      type: "text",
      label: "Name or text (optional)",
      required: false,
      maxChars: 40,
    },
  ],
  "Custom Pens": [
    {
      key: "engrave_text",
      type: "text",
      label: "Text to engrave",
      required: true,
      maxChars: 35,
      hint: "Name, message, or short quote. Max 35 characters.",
    },
  ],
  "Photo Fridge Magnets": [
    {
      key: "photos",
      type: "image",
      label: "Your photos",
      required: true,
      hint: "Upload all photos in one file (collage) or individually. We'll arrange them.",
      multiple: true,
      maxFiles: 16,
    },
    {
      key: "caption",
      type: "text",
      label: "Caption or name (optional)",
      required: false,
      maxChars: 30,
    },
  ],
  "Polaroid-Style Prints": [
    {
      key: "photos",
      type: "image",
      label: "Your photos",
      required: true,
      hint: "Upload up to 30 photos. We print them exactly as you upload.",
      multiple: true,
      maxFiles: 30,
    },
    {
      key: "caption",
      type: "boolean",
      label: "Add captions below photos?",
      required: false,
    },
    {
      key: "notes",
      type: "textarea",
      label: "Caption text (if yes above)",
      required: false,
      maxChars: 500,
      hint: "List captions in order, one per line",
    },
  ],
  "Customised Coasters": [
    {
      key: "photo",
      type: "image",
      label: "Photo or design",
      required: false,
    },
    {
      key: "name_text",
      type: "text",
      label: "Name, monogram or text",
      required: true,
      maxChars: 30,
    },
    {
      key: "sub_text",
      type: "text",
      label: "Sub text (optional)",
      required: false,
      maxChars: 40,
      hint: "e.g. wedding date or family name",
    },
  ],
  "Personalised Cushions": [
    {
      key: "photo",
      type: "image",
      label: "Your photo",
      required: true,
      hint: "High resolution photo. Minimum 1500px on shortest side.",
    },
    {
      key: "name",
      type: "text",
      label: "Name or text (optional)",
      required: false,
      maxChars: 40,
    },
  ],
  "Custom Mugs & Sippers": [
    {
      key: "photo",
      type: "image",
      label: "Your photo",
      required: true,
      hint: "Clear photo. Will wrap around the mug.",
    },
    {
      key: "name",
      type: "text",
      label: "Name",
      required: false,
      maxChars: 30,
    },
    {
      key: "message",
      type: "textarea",
      label: "Message (optional)",
      required: false,
      maxChars: 80,
    },
  ],
  "Branded Caps": [
    {
      key: "logo_file",
      type: "image",
      label: "Your logo",
      required: true,
      hint: "PNG with transparent background preferred. High resolution.",
    },
    {
      key: "text",
      type: "text",
      label: "Text (if no logo)",
      required: false,
      maxChars: 20,
    },
    {
      key: "notes",
      type: "textarea",
      label: "Design notes",
      required: false,
      maxChars: 200,
    },
  ],
  "Branded T-Shirts": [
    {
      key: "logo_file",
      type: "image",
      label: "Your logo or design",
      required: true,
      hint: "PNG with transparent background for best results.",
    },
    {
      key: "name_text",
      type: "text",
      label: "Name or text under logo",
      required: false,
      maxChars: 30,
    },
    {
      key: "notes",
      type: "textarea",
      label: "Print placement notes",
      required: false,
      maxChars: 200,
    },
  ],
};

/** Seed + runtime: resolve personalization fields for a catalog subcategory name. */
export function customizationFieldsForSubcategory(subcategoryName: string): CustomizationFieldDef[] {
  const row = BY_SUBCATEGORY[subcategoryName];
  return row ? row.map((f) => ({ ...f })) : [];
}
