import type { HydratedDocument } from "mongoose";
import type { Types } from "mongoose";
import type { CategoryDoc } from "@/lib/models/Category";
import type { FieldType } from "@/lib/models/schema-field-constants";

type SeedVariant = {
  displayName: string;
  hexCode: string;
  skuSuffix: string;
  stock: number;
  sizes?: { size: string; stock: number }[];
};

/** Image keys must match `IMG` in prisma/seed.ts */
type ImgKey =
  | "chocolate"
  | "sticker"
  | "tissue"
  | "bottle"
  | "calendar"
  | "keychain"
  | "plaque"
  | "topper"
  | "bagtag"
  | "nameplate"
  | "magnet"
  | "journal"
  | "bookmark"
  | "organizer"
  | "mousepad"
  | "pen"
  | "flexmagnet"
  | "polaroid"
  | "coaster"
  | "cushion"
  | "mug"
  | "cap"
  | "tshirt";

type SeedProduct = {
  name: string;
  brand: string;
  description: string;
  mrp: number;
  price: number;
  imageKey: ImgKey;
  imageKey2?: ImgKey;
  hasColourVariants: boolean;
  hasSizePricing: boolean;
  sizesNotApplicable: boolean;
  variants: SeedVariant[];
  specValues: Record<string, string | number | boolean>;
};

type SeedSubInput = {
  categoryId: Types.ObjectId;
  name: string;
  displayOrder: number;
  description?: string;
  fields: {
    key: string;
    label: string;
    type: FieldType;
    options?: string[];
    isHighlight: boolean;
    isRequired: boolean;
    displayOrder: number;
  }[];
  products: SeedProduct[];
};

export async function runCatalogBlocks(args: {
  catPaper: HydratedDocument<CategoryDoc>;
  catAcrylic: HydratedDocument<CategoryDoc>;
  catStationery: HydratedDocument<CategoryDoc>;
  catDecor: HydratedDocument<CategoryDoc>;
  catTextile: HydratedDocument<CategoryDoc>;
  seedSubcategory: (data: SeedSubInput) => Promise<void>;
}): Promise<void> {
  const { catPaper, catAcrylic, catStationery, catDecor, catTextile, seedSubcategory } = args;

  await seedSubcategory({
    categoryId: catPaper._id,
    name: "Chocolate Wrappers",
    displayOrder: 1,
    description:
      "Custom printed chocolate wrappers for birthdays, weddings, and corporate gifting.",
    fields: [
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Glossy", "Matte", "Foil Gold", "Foil Silver"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "bar_size",
        label: "Bar size",
        type: "select",
        options: ["5g", "10g", "20g", "40g"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "occasion",
        label: "Occasion",
        type: "select",
        options: ["Birthday", "Wedding", "Corporate", "Baby Shower", "Anniversary"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "min_qty",
        label: "Minimum qty",
        type: "select",
        options: ["25 pcs", "50 pcs", "100 pcs"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Glossy paper", "Matte paper", "Foil laminate"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Chocolate Wrapper — Birthday Design Pack of 25",
        brand: "Prisbo Creations",
        description:
          "Transform any chocolate bar into a special gift. Our {{occasion}} chocolate wrappers are printed in {{finish}} finish on premium paper. Pack of {{min_qty}}. Fully customisable with name, photo, or logo.",
        mrp: 399,
        price: 249,
        imageKey: "chocolate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 500 }],
        specValues: {
          finish: "Glossy",
          bar_size: "20g",
          occasion: "Birthday",
          min_qty: "25 pcs",
          custom: "Name + Photo",
          material: "Glossy paper",
        },
      },
      {
        name: "Wedding Favour Chocolate Wrapper — Foil Gold Finish Pack of 50",
        brand: "Prisbo Creations",
        description:
          "Elegant {{finish}} chocolate wrappers for your {{occasion}}. Each wrapper is personalised with your names and date. Pack of {{min_qty}}.",
        mrp: 699,
        price: 499,
        imageKey: "chocolate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          finish: "Foil Gold",
          bar_size: "20g",
          occasion: "Wedding",
          min_qty: "50 pcs",
          custom: "Names + Date",
          material: "Foil laminate",
        },
      },
      {
        name: "Corporate Branding Chocolate Wrapper — Logo Print Pack of 100",
        brand: "Prisbo Creations",
        description:
          "Put your brand on every chocolate. {{finish}} finish wrappers with your {{custom}}. Minimum {{min_qty}}. Perfect for {{occasion}} gifting.",
        mrp: 999,
        price: 749,
        imageKey: "chocolate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          finish: "Matte",
          bar_size: "40g",
          occasion: "Corporate",
          min_qty: "100 pcs",
          custom: "Company logo",
          material: "Matte paper",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catPaper._id,
    name: "Custom Stickers & Labels",
    displayOrder: 2,
    description: "Die-cut custom stickers and labels for small businesses, packaging, and gifting.",
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Vinyl", "Transparent vinyl", "Kraft paper", "White matte paper"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Circle", "Square", "Rectangle", "Die-cut", "Custom shape"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Glossy", "Matte", "Holographic", "Glitter"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["3cm", "5cm", "7cm", "Custom"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "min_qty",
        label: "Minimum qty",
        type: "select",
        options: ["50 pcs", "100 pcs", "250 pcs", "500 pcs"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "waterproof",
        label: "Waterproof",
        type: "boolean",
        options: [],
        isHighlight: false,
        isRequired: false,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Custom Logo Stickers — Vinyl Glossy Circle 5cm Pack of 100",
        brand: "Prisbo Creations",
        description:
          "Stick your brand everywhere. {{material}} stickers in {{finish}} finish, {{shape}} shape, {{size}}. Pack of {{min_qty}}. Waterproof: {{waterproof}}.",
        mrp: 499,
        price: 299,
        imageKey: "sticker",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 1000 }],
        specValues: {
          material: "Vinyl",
          shape: "Circle",
          finish: "Glossy",
          size: "5cm",
          min_qty: "100 pcs",
          waterproof: true,
        },
      },
      {
        name: "Thank You Sticker Labels — Kraft Paper Matte Pack of 50",
        brand: "Prisbo Creations",
        description:
          "Personalised {{finish}} {{shape}} stickers in {{material}}. {{size}} diameter. Pack of {{min_qty}}. Perfect for packaging and gifting.",
        mrp: 299,
        price: 179,
        imageKey: "sticker",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 800 }],
        specValues: {
          material: "Kraft paper",
          shape: "Circle",
          finish: "Matte",
          size: "5cm",
          min_qty: "50 pcs",
          waterproof: false,
        },
      },
      {
        name: "Holographic Die-cut Custom Stickers — 7cm Pack of 50",
        brand: "Prisbo Creations",
        description: "Eye-catching {{finish}} {{shape}} stickers in {{material}}. {{size}}. Pack of {{min_qty}}.",
        mrp: 599,
        price: 399,
        imageKey: "sticker",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 500 }],
        specValues: {
          material: "Vinyl",
          shape: "Die-cut",
          finish: "Holographic",
          size: "7cm",
          min_qty: "50 pcs",
          waterproof: true,
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catPaper._id,
    name: "Branded Tissue Paper",
    displayOrder: 3,
    fields: [
      {
        key: "sheet_size",
        label: "Sheet size",
        type: "select",
        options: ["50×70cm", "35×50cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "print_colour",
        label: "Print colour",
        type: "select",
        options: ["1 colour", "2 colour", "Full colour"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "pack_size",
        label: "Pack size",
        type: "select",
        options: ["100 sheets", "250 sheets", "500 sheets"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
    ],
    products: [
      {
        name: "Branded Logo Tissue Paper — Full Colour 50×70cm Pack of 100",
        brand: "Prisbo Creations",
        description:
          "Elevate your packaging with branded {{print_colour}} tissue paper. {{sheet_size}} sheets. Pack of {{pack_size}}. Customised with {{custom}}.",
        mrp: 599,
        price: 399,
        imageKey: "tissue",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 400 }],
        specValues: {
          sheet_size: "50×70cm",
          print_colour: "Full colour",
          pack_size: "100 sheets",
          custom: "Logo + brand name",
        },
      },
      {
        name: "Custom Pattern Tissue Paper — 2 Colour Pack of 250",
        brand: "Prisbo Creations",
        description:
          "{{print_colour}} printed {{sheet_size}} tissue paper. Pack of {{pack_size}}. Customised with {{custom}}.",
        mrp: 899,
        price: 649,
        imageKey: "tissue",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          sheet_size: "50×70cm",
          print_colour: "2 colour",
          pack_size: "250 sheets",
          custom: "Pattern + logo",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catPaper._id,
    name: "Custom Bottle Labels",
    displayOrder: 4,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Waterproof vinyl", "Matte paper", "Gloss paper"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "label_type",
        label: "Label type",
        type: "select",
        options: ["Wine bottle 90×120mm", "Water bottle 65×100mm", "Custom size"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Glossy", "Matte", "Textured"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "occasion",
        label: "Occasion",
        type: "select",
        options: ["Wedding", "Birthday", "Corporate", "Party", "Anniversary"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "min_qty",
        label: "Minimum qty",
        type: "select",
        options: ["25 pcs", "50 pcs", "100 pcs"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
    ],
    products: [
      {
        name: "Custom Wine Bottle Label — Wedding Personalised Waterproof Pack of 25",
        brand: "Prisbo Creations",
        description:
          "Personalised {{finish}} {{label_type}} labels in {{material}}. Perfect for {{occasion}}. Pack of {{min_qty}}.",
        mrp: 699,
        price: 449,
        imageKey: "bottle",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 400 }],
        specValues: {
          material: "Waterproof vinyl",
          label_type: "Wine bottle 90×120mm",
          finish: "Glossy",
          occasion: "Wedding",
          min_qty: "25 pcs",
        },
      },
      {
        name: "Personalised Water Bottle Label — Birthday Party Pack of 50",
        brand: "Prisbo Creations",
        description:
          "Custom {{finish}} {{label_type}} in {{material}}. {{occasion}} design. Pack of {{min_qty}}.",
        mrp: 499,
        price: 299,
        imageKey: "bottle",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 500 }],
        specValues: {
          material: "Matte paper",
          label_type: "Water bottle 65×100mm",
          finish: "Matte",
          occasion: "Birthday",
          min_qty: "50 pcs",
        },
      },
      {
        name: "Corporate Event Bottle Label — Logo Branded Pack of 100",
        brand: "Prisbo Creations",
        description:
          "Brand every bottle at your {{occasion}}. {{finish}} {{material}} labels. Pack of {{min_qty}}.",
        mrp: 799,
        price: 549,
        imageKey: "bottle",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          material: "Waterproof vinyl",
          label_type: "Water bottle 65×100mm",
          finish: "Glossy",
          occasion: "Corporate",
          min_qty: "100 pcs",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catPaper._id,
    name: "Tear-off Calendars",
    displayOrder: 5,
    fields: [
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["A5 (148×210mm)", "A6 (105×148mm)"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "page_type",
        label: "Page type",
        type: "select",
        options: ["365 daily", "52 weekly", "12 monthly"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "binding",
        label: "Binding",
        type: "select",
        options: ["Wire-o", "Spiral", "Staple"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "base",
        label: "Stand/base",
        type: "select",
        options: ["None", "Fold-back stand", "Wooden base"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 3,
      },
      {
        key: "photos",
        label: "Photo slots",
        type: "select",
        options: ["1 cover photo", "12 monthly photos", "Single full-bleed"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
    ],
    products: [
      {
        name: "Personalised Desk Calendar 2026 — A5 365 Daily Tear-off",
        brand: "Prisbo Creations",
        description:
          "A {{size}} {{page_type}} tear-off desk calendar. Bound with {{binding}}. {{base}} stand included. {{photos}} customisation.",
        mrp: 699,
        price: 449,
        imageKey: "calendar",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          size: "A5 (148×210mm)",
          page_type: "365 daily",
          binding: "Wire-o",
          base: "Fold-back stand",
          photos: "1 cover photo",
        },
      },
      {
        name: "Photo Desk Calendar — A5 12 Monthly Pages with Wooden Base",
        brand: "Prisbo Creations",
        description:
          "{{size}} {{page_type}} calendar with {{photos}}. {{binding}} binding. {{base}}.",
        mrp: 999,
        price: 699,
        imageKey: "calendar",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          size: "A5 (148×210mm)",
          page_type: "12 monthly",
          binding: "Wire-o",
          base: "Wooden base",
          photos: "12 monthly photos",
        },
      },
      {
        name: "Mini Pocket Calendar — A6 Weekly Tear-off Personalised",
        brand: "Prisbo Creations",
        description: "Compact {{size}} {{page_type}} calendar. {{binding}} bound. {{base}}.",
        mrp: 399,
        price: 249,
        imageKey: "calendar",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          size: "A6 (105×148mm)",
          page_type: "52 weekly",
          binding: "Staple",
          base: "None",
          photos: "1 cover photo",
        },
      },
    ],
  });

  console.log("✓ Paper & Packaging done");

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Photo Keychains",
    displayOrder: 1,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Clear acrylic 3mm", "Frosted acrylic", "Coloured acrylic"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Circle", "Heart", "Rectangle", "Oval", "Custom"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Clear glossy", "Frosted", "Mirror gold", "Mirror silver"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "feature",
        label: "Special feature",
        type: "select",
        options: ["Spotify scan code", "QR code", "Photo only", "Name only"],
        isHighlight: true,
        isRequired: false,
        displayOrder: 3,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["5cm", "7cm", "10cm"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "chain",
        label: "Chain type",
        type: "select",
        options: ["Silver keyring", "Gold keyring", "Ball chain", "Lobster clasp"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 6,
      },
    ],
    products: [
      {
        name: "Personalised Spotify Song Keychain — Acrylic Heart with Scan Code",
        brand: "Prisbo Creations",
        description:
          "A personalised {{finish}} {{material}} keychain in {{shape}} shape, {{size}}. Features a real {{feature}} that actually scans. Comes with a {{chain}}. Customised with {{custom}}.",
        mrp: 699,
        price: 349,
        imageKey: "keychain",
        imageKey2: "keychain",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 120 }],
        specValues: {
          material: "Clear acrylic 3mm",
          shape: "Heart",
          finish: "Clear glossy",
          feature: "Spotify scan code",
          size: "7cm",
          chain: "Gold keyring",
          custom: "Photo + song name",
        },
      },
      {
        name: "Custom Photo Keychain — Acrylic Circle Mirror Gold Finish",
        brand: "Prisbo Creations",
        description:
          "{{finish}} {{material}} keychain, {{shape}} shape, {{size}}. {{chain}} included. Customised with {{custom}}.",
        mrp: 599,
        price: 299,
        imageKey: "keychain",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFD700", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          material: "Clear acrylic 3mm",
          shape: "Circle",
          finish: "Mirror gold",
          feature: "Photo only",
          size: "7cm",
          chain: "Gold keyring",
          custom: "Photo + name",
        },
      },
      {
        name: "Couple Photo Keychain Set — Acrylic Rectangle Frosted 10cm",
        brand: "Prisbo Creations",
        description:
          "A set of 2 personalised {{finish}} {{material}} keychains, {{shape}} shape, {{size}}. {{chain}} on each.",
        mrp: 999,
        price: 549,
        imageKey: "keychain",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#F5F5F5", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          material: "Frosted acrylic",
          shape: "Rectangle",
          finish: "Frosted",
          feature: "Photo only",
          size: "10cm",
          chain: "Silver keyring",
          custom: "Couple photo + names",
        },
      },
      {
        name: "Kids Name Keychain — Acrylic Custom Shape 5cm",
        brand: "Prisbo Creations",
        description:
          "Adorable personalised {{finish}} {{material}} keychain in a {{shape}} shape, {{size}}. Comes with {{chain}}.",
        mrp: 499,
        price: 249,
        imageKey: "keychain",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          material: "Clear acrylic 3mm",
          shape: "Custom",
          finish: "Clear glossy",
          feature: "Name only",
          size: "5cm",
          chain: "Silver keyring",
          custom: "Name + cute graphic",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Desk Plaques",
    displayOrder: 2,
    fields: [
      {
        key: "acrylic_panel",
        label: "Acrylic panel",
        type: "select",
        options: ["Clear", "Frosted", "Smoked", "Black", "Tinted colour"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "base",
        label: "Base type",
        type: "select",
        options: ["Wooden base", "LED light base (RGB)", "Metal stand", "Acrylic block"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["A5 (148×210mm)", "A4 (210×297mm)", "Custom"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "print_method",
        label: "Print method",
        type: "select",
        options: ["UV direct print", "Laser engraved"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "occasion",
        label: "Occasion",
        type: "select",
        options: ["Office desk", "Awards", "Birthday", "Home decor", "Corporate"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Acrylic Desk Plaque — LED Light Base RGB Name Frame",
        brand: "Prisbo Creations",
        description:
          "A premium {{acrylic_panel}} acrylic plaque with {{base}}. {{size}} size, {{print_method}}. Perfect for {{occasion}}. Customised with {{custom}}.",
        mrp: 1299,
        price: 799,
        imageKey: "plaque",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8EDF5", skuSuffix: "DEF", stock: 60 }],
        specValues: {
          acrylic_panel: "Clear",
          base: "LED light base (RGB)",
          size: "A5 (148×210mm)",
          print_method: "UV direct print",
          occasion: "Office desk",
          custom: "Name + designation + photo",
        },
      },
      {
        name: "Custom Acrylic Name Plaque — Wooden Base Office Desk A5",
        brand: "Prisbo Creations",
        description:
          "{{acrylic_panel}} acrylic plaque on a {{base}}. {{size}}, {{print_method}}. Customised with {{custom}}.",
        mrp: 899,
        price: 549,
        imageKey: "plaque",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#F5F0E8", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          acrylic_panel: "Clear",
          base: "Wooden base",
          size: "A5 (148×210mm)",
          print_method: "UV direct print",
          occasion: "Office desk",
          custom: "Name + designation",
        },
      },
      {
        name: "Frosted Acrylic Award Plaque — Metal Stand A4",
        brand: "Prisbo Creations",
        description:
          "{{acrylic_panel}} acrylic on {{base}}, {{size}}. Engraved using {{print_method}}. Customised with {{custom}}.",
        mrp: 1499,
        price: 999,
        imageKey: "plaque",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#F5F5F5", skuSuffix: "DEF", stock: 40 }],
        specValues: {
          acrylic_panel: "Frosted",
          base: "Metal stand",
          size: "A4 (210×297mm)",
          print_method: "Laser engraved",
          occasion: "Awards",
          custom: "Award title + recipient name + date",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Cake Toppers",
    displayOrder: 3,
    fields: [
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: [
          "Glitter gold",
          "Glitter silver",
          "Mirror gold",
          "Mirror silver",
          "Matte white",
          "Rose gold",
        ],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "style",
        label: "Style",
        type: "select",
        options: ["Name only", "Name + Age", "Name + Date", "Custom silhouette"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "height",
        label: "Height",
        type: "select",
        options: ["10cm", "15cm", "20cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "font",
        label: "Font style",
        type: "select",
        options: ["Script", "Bold", "Serif", "Sans"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 3,
      },
      {
        key: "sticks",
        label: "Sticks",
        type: "select",
        options: ["White sticks", "Gold sticks"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Acrylic Cake Topper — Mirror Gold Name + Age 15cm",
        brand: "Prisbo Creations",
        description:
          "A gorgeous {{finish}} acrylic cake topper in {{style}} style, {{height}} tall. {{font}} font. Comes with {{sticks}}. Customised with {{custom}}.",
        mrp: 499,
        price: 249,
        imageKey: "topper",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFD700", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          finish: "Mirror gold",
          style: "Name + Age",
          height: "15cm",
          font: "Script",
          sticks: "Gold sticks",
          custom: "Name + age number",
        },
      },
      {
        name: "Wedding Cake Topper — Rose Gold Mr & Mrs Script Acrylic 20cm",
        brand: "Prisbo Creations",
        description:
          "Elegant {{finish}} acrylic wedding cake topper, {{style}}, {{height}} tall. {{font}} font. {{sticks}} included.",
        mrp: 699,
        price: 399,
        imageKey: "topper",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#B76E79", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          finish: "Rose gold",
          style: "Custom silhouette",
          height: "20cm",
          font: "Script",
          sticks: "Gold sticks",
          custom: "Mr & Mrs + surname",
        },
      },
      {
        name: "Glitter Silver Birthday Cake Topper — Name Only 10cm",
        brand: "Prisbo Creations",
        description:
          "{{finish}} acrylic cake topper with {{style}} design, {{height}} height. {{font}} font on {{sticks}}.",
        mrp: 349,
        price: 179,
        imageKey: "topper",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#C0C0C0", skuSuffix: "DEF", stock: 250 }],
        specValues: {
          finish: "Glitter silver",
          style: "Name only",
          height: "10cm",
          font: "Bold",
          sticks: "White sticks",
          custom: "First name",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Custom Bag Tags",
    displayOrder: 4,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Clear acrylic 3mm", "PVC flexible", "Leather"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Rectangle", "Rounded rectangle", "Custom die-cut"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["Standard 10×5cm", "Large 12×7cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "attachment",
        label: "Attachment",
        type: "select",
        options: ["Steel loop", "Ribbon", "Leather strap"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "use_case",
        label: "Use case",
        type: "select",
        options: ["School bag", "Travel luggage", "Gym bag", "Office bag"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Acrylic School Bag Tag — Child Name Clear 10×5cm",
        brand: "Prisbo Creations",
        description:
          "Keep your child safe with a personalised {{material}} {{shape}} bag tag, {{size}}. Comes with {{attachment}}. Perfect for {{use_case}}. Customised with {{custom}}.",
        mrp: 349,
        price: 179,
        imageKey: "bagtag",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          material: "Clear acrylic 3mm",
          shape: "Rounded rectangle",
          size: "Standard 10×5cm",
          attachment: "Steel loop",
          use_case: "School bag",
          custom: "Child name + class",
        },
      },
      {
        name: "Travel Luggage Tag — Custom Name Acrylic 12×7cm with Leather Strap",
        brand: "Prisbo Creations",
        description:
          "Never lose your luggage. {{material}} {{shape}} tag, {{size}}. {{attachment}} for easy attachment. For {{use_case}}.",
        mrp: 499,
        price: 299,
        imageKey: "bagtag",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#8B4513", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          material: "Clear acrylic 3mm",
          shape: "Rectangle",
          size: "Large 12×7cm",
          attachment: "Leather strap",
          use_case: "Travel luggage",
          custom: "Name + contact number",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Acrylic Name Plates",
    displayOrder: 5,
    fields: [
      {
        key: "mount_style",
        label: "Mount style",
        type: "select",
        options: ["Desk stand", "Wall mount", "Door plate"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "panel",
        label: "Acrylic panel",
        type: "select",
        options: ["Clear", "Frosted", "Black", "Tinted colour"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "base",
        label: "Base/stand",
        type: "select",
        options: ["Wooden base", "Metal legs", "Acrylic block", "Wall screws"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["A5", "A4", "Custom"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "print_method",
        label: "Print method",
        type: "select",
        options: ["UV print", "Laser engraved", "Vinyl lettering"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "use_case",
        label: "Use case",
        type: "select",
        options: ["Office desk", "House door", "Hotel room", "Hospital ward"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 6,
      },
    ],
    products: [
      {
        name: "Personalised Acrylic Office Desk Name Plate — Wooden Base Clear A5",
        brand: "Prisbo Creations",
        description:
          "Professional {{panel}} acrylic name plate on a {{base}}, {{size}}. {{print_method}}. Ideal for {{use_case}}. Customised with {{custom}}.",
        mrp: 799,
        price: 499,
        imageKey: "nameplate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#F5F0E8", skuSuffix: "DEF", stock: 100 }],
        specValues: {
          mount_style: "Desk stand",
          panel: "Clear",
          base: "Wooden base",
          size: "A5",
          print_method: "UV print",
          use_case: "Office desk",
          custom: "Name + designation",
        },
      },
      {
        name: "Custom House Door Name Plate — Black Acrylic Wall Mount A5",
        brand: "Prisbo Creations",
        description:
          "Stylish {{panel}} acrylic {{mount_style}}, {{size}}. {{print_method}}. For {{use_case}}. Customised with {{custom}}.",
        mrp: 999,
        price: 649,
        imageKey: "nameplate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#1A1A1A", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          mount_style: "Wall mount",
          panel: "Black",
          base: "Wall screws",
          size: "A5",
          print_method: "Laser engraved",
          use_case: "House door",
          custom: "Family name + house number",
        },
      },
      {
        name: "Frosted Acrylic LED Door Plate — Hotel Room Name Sign Custom",
        brand: "Prisbo Creations",
        description:
          "{{panel}} acrylic {{mount_style}}, {{size}}, with {{base}}. {{print_method}}. Perfect for {{use_case}}.",
        mrp: 1299,
        price: 899,
        imageKey: "nameplate",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#F5F5F5", skuSuffix: "DEF", stock: 50 }],
        specValues: {
          mount_style: "Door plate",
          panel: "Frosted",
          base: "Wall screws",
          size: "A5",
          print_method: "UV print",
          use_case: "Hotel room",
          custom: "Room number + name",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catAcrylic._id,
    name: "Acrylic Fridge Magnets",
    displayOrder: 6,
    fields: [
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Rectangle", "Circle", "Rounded square", "Custom"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["5×5cm", "7×5cm", "10×7cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Clear glossy", "Frosted back"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "magnet",
        label: "Magnet strength",
        type: "select",
        options: ["Standard ferrite", "Strong neodymium"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
    ],
    products: [
      {
        name: "Custom Photo Acrylic Fridge Magnet — Clear Glossy Rectangle 10×7cm",
        brand: "Prisbo Creations",
        description:
          "A rigid {{finish}} acrylic fridge magnet in {{shape}} shape, {{size}}. {{magnet}} strength. Customised with {{custom}}.",
        mrp: 399,
        price: 199,
        imageKey: "magnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          shape: "Rectangle",
          size: "10×7cm",
          finish: "Clear glossy",
          magnet: "Standard ferrite",
          custom: "Family photo + names",
        },
      },
      {
        name: "Personalised Acrylic Fridge Magnet — Circle 7×5cm Neodymium",
        brand: "Prisbo Creations",
        description:
          "{{finish}} {{shape}} acrylic magnet, {{size}}, with {{magnet}} magnet. Customised with {{custom}}.",
        mrp: 299,
        price: 149,
        imageKey: "magnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 400 }],
        specValues: {
          shape: "Circle",
          size: "7×5cm",
          finish: "Clear glossy",
          magnet: "Strong neodymium",
          custom: "Photo + name",
        },
      },
      {
        name: "Set of 4 Acrylic Fridge Magnets — Custom Photo Collage Pack",
        brand: "Prisbo Creations",
        description:
          "Set of 4 {{finish}} {{shape}} acrylic magnets, {{size}} each. {{magnet}} strength. Customised with {{custom}}.",
        mrp: 699,
        price: 399,
        imageKey: "magnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8F4F8", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          shape: "Rectangle",
          size: "7×5cm",
          finish: "Clear glossy",
          magnet: "Standard ferrite",
          custom: "4 different photos",
        },
      },
    ],
  });

  console.log("✓ Acrylic & Resin Items done");

  await seedSubcategory({
    categoryId: catStationery._id,
    name: "Journals & Notebooks",
    displayOrder: 1,
    fields: [
      {
        key: "cover_material",
        label: "Cover material",
        type: "select",
        options: ["Faux leather", "Kraft paper", "Linen", "Canvas"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["A5 (148×210mm)", "B5 (176×250mm)"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "pages",
        label: "Pages",
        type: "select",
        options: ["100 ruled", "150 ruled", "200 blank", "Dotted grid"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "cover_type",
        label: "Cover type",
        type: "select",
        options: ["Hardcover", "Softcover"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "binding",
        label: "Binding",
        type: "select",
        options: ["Smyth sewn", "Perfect bound", "Spiral"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Faux Leather Journal A5 — Name Embossed Hardcover 150 Pages",
        brand: "Prisbo Creations",
        description:
          "A premium {{cover_type}} {{cover_material}} journal, {{size}}, with {{pages}} pages. {{binding}} bound. Customised with {{custom}}.",
        mrp: 899,
        price: 599,
        imageKey: "journal",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Dark Brown", hexCode: "#5C3317", skuSuffix: "BRN", stock: 80 },
          { displayName: "Midnight Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 80 },
          { displayName: "Dusty Rose", hexCode: "#C17A8A", skuSuffix: "RSE", stock: 60 },
        ],
        specValues: {
          cover_material: "Faux leather",
          size: "A5 (148×210mm)",
          pages: "150 ruled",
          cover_type: "Hardcover",
          binding: "Smyth sewn",
          custom: "Name engraving on cover",
        },
      },
      {
        name: "Kraft Paper Notebook A5 — Custom Printed Cover 100 Pages",
        brand: "Prisbo Creations",
        description:
          "{{cover_type}} {{cover_material}} notebook, {{size}}, {{pages}} pages. {{binding}} bound. Customised with {{custom}}.",
        mrp: 599,
        price: 349,
        imageKey: "journal",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Natural Kraft", hexCode: "#C4A265", skuSuffix: "DEF", stock: 120 }],
        specValues: {
          cover_material: "Kraft paper",
          size: "A5 (148×210mm)",
          pages: "100 ruled",
          cover_type: "Softcover",
          binding: "Perfect bound",
          custom: "Custom illustration + name",
        },
      },
      {
        name: "Dotted Grid Journal — Linen Cover B5 Personalised Name",
        brand: "Prisbo Creations",
        description:
          "{{cover_type}} {{cover_material}} journal, {{size}}, with {{pages}}. {{binding}} bound. Perfect for bullet journaling. Customised with {{custom}}.",
        mrp: 799,
        price: 499,
        imageKey: "journal",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Sage Green", hexCode: "#8FAF8A", skuSuffix: "GRN", stock: 70 },
          { displayName: "Sky Blue", hexCode: "#87CEEB", skuSuffix: "BLU", stock: 70 },
        ],
        specValues: {
          cover_material: "Linen",
          size: "B5 (176×250mm)",
          pages: "Dotted grid",
          cover_type: "Hardcover",
          binding: "Smyth sewn",
          custom: "Name + monogram",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catStationery._id,
    name: "Custom Bookmarks",
    displayOrder: 2,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Acrylic 2mm", "Laminated paper", "PVC"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Glossy", "Matte"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "tassel",
        label: "Tassel colour",
        type: "select",
        options: ["Gold", "Silver", "Black", "White", "Rose gold", "Custom"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["Standard 5×18cm", "Mini 4×10cm"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
    ],
    products: [
      {
        name: "Personalised Photo Bookmark — Acrylic Glossy with Gold Tassel 5×18cm",
        brand: "Prisbo Creations",
        description:
          "A beautiful {{material}} {{finish}} bookmark, {{size}}, with a {{tassel}} silk tassel. Customised with {{custom}}.",
        mrp: 299,
        price: 149,
        imageKey: "bookmark",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFD700", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          material: "Acrylic 2mm",
          finish: "Glossy",
          tassel: "Gold",
          size: "Standard 5×18cm",
          custom: "Photo + inspirational quote",
        },
      },
      {
        name: "Inspirational Quote Bookmark — Laminated Matte Pack of 5",
        brand: "Prisbo Creations",
        description:
          "Set of 5 {{material}} {{finish}} bookmarks, {{size}}, each with a {{tassel}} tassel. Customised with {{custom}}.",
        mrp: 499,
        price: 279,
        imageKey: "bookmark",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#C0C0C0", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          material: "Laminated paper",
          finish: "Matte",
          tassel: "Silver",
          size: "Standard 5×18cm",
          custom: "5 different quotes",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catStationery._id,
    name: "Desk Organizers",
    displayOrder: 3,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["MDF 6mm", "Acrylic 3mm", "Bamboo"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "compartments",
        label: "Compartments",
        type: "select",
        options: ["3 slot", "5 slot", "7 slot with drawer"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "colour",
        label: "Colour",
        type: "select",
        options: ["Natural MDF", "Black", "White", "Pastel pink", "Custom"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "engraving",
        label: "Engraving",
        type: "select",
        options: ["Laser engraved name", "UV printed logo", "Plain"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 3,
      },
      {
        key: "assembly",
        label: "Assembly",
        type: "select",
        options: ["Flat-pack (self-assemble)", "Pre-assembled"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: false,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised MDF Desk Organizer — 5 Slot Laser Engraved Name",
        brand: "Prisbo Creations",
        description:
          "A {{colour}} {{material}} desk organizer with {{compartments}}. {{engraving}}. {{assembly}}. Customised with {{custom}}.",
        mrp: 1299,
        price: 849,
        imageKey: "organizer",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Natural MDF", hexCode: "#C4A265", skuSuffix: "NAT", stock: 50 },
          { displayName: "Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 50 },
          { displayName: "White", hexCode: "#FFFFFF", skuSuffix: "WHT", stock: 50 },
        ],
        specValues: {
          material: "MDF 6mm",
          compartments: "5 slot",
          colour: "Natural MDF",
          engraving: "Laser engraved name",
          assembly: "Flat-pack (self-assemble)",
          custom: "Name + workspace quote",
        },
      },
      {
        name: "Acrylic Desk Organizer 3 Slot — Clear with Name UV Print",
        brand: "Prisbo Creations",
        description:
          "{{colour}} {{material}} organizer, {{compartments}}. {{engraving}}. {{assembly}}.",
        mrp: 999,
        price: 649,
        imageKey: "organizer",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Clear", hexCode: "#E8EDF5", skuSuffix: "DEF", stock: 60 }],
        specValues: {
          material: "Acrylic 3mm",
          compartments: "3 slot",
          colour: "Natural MDF",
          engraving: "UV printed logo",
          assembly: "Pre-assembled",
          custom: "Name or logo",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catStationery._id,
    name: "Mousepads",
    displayOrder: 4,
    fields: [
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["Small 20×24cm", "Medium 30×25cm", "Large 40×80cm", "XL desk mat 90×40cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "select",
        options: ["3mm standard", "5mm thick"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "edge",
        label: "Edge finish",
        type: "select",
        options: ["Stitched edge", "Unfinished cut edge"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
    ],
    products: [
      {
        name: "Custom Photo Mousepad — Family Photo Medium 30×25cm Stitched Edge",
        brand: "Prisbo Creations",
        description:
          "Personalised {{size}} mousepad with {{thickness}} rubber base and {{edge}}. Print anything — {{custom}}.",
        mrp: 599,
        price: 349,
        imageKey: "mousepad",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          size: "Medium 30×25cm",
          thickness: "3mm standard",
          edge: "Stitched edge",
          custom: "Family photo",
        },
      },
      {
        name: "XL Desk Mat — Custom Workspace Aesthetic 90×40cm",
        brand: "Prisbo Creations",
        description:
          "Full desk coverage with our {{size}} {{thickness}} desk mat. {{edge}}. Custom {{custom}} design.",
        mrp: 1299,
        price: 849,
        imageKey: "mousepad",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          size: "XL desk mat 90×40cm",
          thickness: "5mm thick",
          edge: "Stitched edge",
          custom: "Custom workspace aesthetic",
        },
      },
      {
        name: "Kids Name Mousepad — Photo + Name Small 20×24cm",
        brand: "Prisbo Creations",
        description:
          "Fun {{size}} {{thickness}} mousepad with {{edge}} for kids. Customised with {{custom}}.",
        mrp: 399,
        price: 229,
        imageKey: "mousepad",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          size: "Small 20×24cm",
          thickness: "3mm standard",
          edge: "Stitched edge",
          custom: "Child photo + name",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catStationery._id,
    name: "Custom Pens",
    displayOrder: 5,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Metal (aluminium)", "Bamboo", "Rosewood", "Plastic ABS"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "colour",
        label: "Pen colour",
        type: "select",
        options: ["Silver", "Gold", "Gunmetal", "Matte black", "Rose gold"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "pen_type",
        label: "Pen type",
        type: "select",
        options: ["Ballpoint", "Rollerball", "Stylus tip"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "pack_option",
        label: "Pack option",
        type: "select",
        options: ["Single", "Pair", "Set of 5 (gift box)"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "ink",
        label: "Ink colour",
        type: "select",
        options: ["Black", "Blue", "Red"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Laser Engraved Metal Pen — Personalised Name Ballpoint Gunmetal",
        brand: "Prisbo Creations",
        description:
          "A premium {{material}} {{pen_type}} pen in {{colour}}. Laser engraved with {{custom}}. {{pack_option}} packaging. {{ink}} ink.",
        mrp: 599,
        price: 349,
        imageKey: "pen",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Gunmetal", hexCode: "#6B6B6B", skuSuffix: "GUN", stock: 150 },
          { displayName: "Gold", hexCode: "#FFD700", skuSuffix: "GLD", stock: 150 },
          { displayName: "Matte Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 150 },
        ],
        specValues: {
          material: "Metal (aluminium)",
          colour: "Gunmetal",
          pen_type: "Ballpoint",
          pack_option: "Single",
          ink: "Black",
          custom: "Name or short message",
        },
      },
      {
        name: "Bamboo Engraved Pen Set of 5 — Corporate Gift Box",
        brand: "Prisbo Creations",
        description:
          "Set of 5 eco-friendly {{material}} {{pen_type}} pens, each laser engraved with {{custom}}. Comes in a {{pack_option}}.",
        mrp: 1499,
        price: 999,
        imageKey: "pen",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Natural Bamboo", hexCode: "#C4A265", skuSuffix: "DEF", stock: 60 }],
        specValues: {
          material: "Bamboo",
          colour: "Silver",
          pen_type: "Ballpoint",
          pack_option: "Set of 5 (gift box)",
          ink: "Black",
          custom: "Company name or logo",
        },
      },
      {
        name: "Personalised Rosewood Rollerball Pen — Name Engraved Premium Gift",
        brand: "Prisbo Creations",
        description:
          "A luxurious {{material}} {{pen_type}} pen. Engraved with {{custom}}. {{pack_option}} with gift packaging.",
        mrp: 999,
        price: 699,
        imageKey: "pen",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Rosewood", hexCode: "#65000B", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          material: "Rosewood",
          colour: "Gold",
          pen_type: "Rollerball",
          pack_option: "Single",
          ink: "Black",
          custom: "Name + short message",
        },
      },
    ],
  });

  console.log("✓ Stationery & Desk Accessories done");

  await seedSubcategory({
    categoryId: catDecor._id,
    name: "Photo Fridge Magnets",
    displayOrder: 1,
    fields: [
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Wallet size 5×8cm", "Square 10×10cm", "Polaroid style 7×10cm", "Heart", "Round"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Glossy", "Matte"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "pack",
        label: "Pack",
        type: "select",
        options: ["Single", "Set of 4", "Set of 9", "Set of 16"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
    ],
    products: [
      {
        name: "Custom Photo Fridge Magnets — Glossy Polaroid Style Set of 9",
        brand: "Prisbo Creations",
        description: "Flexible {{finish}} fridge magnets in {{shape}} format. {{pack}}. Customised with {{custom}}.",
        mrp: 699,
        price: 399,
        imageKey: "flexmagnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          shape: "Polaroid style 7×10cm",
          finish: "Glossy",
          pack: "Set of 9",
          custom: "9 different family photos",
        },
      },
      {
        name: "Personalised Fridge Magnet Set — Square Photo 10×10cm Set of 4",
        brand: "Prisbo Creations",
        description: "{{finish}} {{shape}} photo magnets. {{pack}}. Customised with {{custom}}.",
        mrp: 499,
        price: 279,
        imageKey: "flexmagnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 300 }],
        specValues: {
          shape: "Square 10×10cm",
          finish: "Glossy",
          pack: "Set of 4",
          custom: "4 family photos",
        },
      },
      {
        name: "Heart Shaped Photo Fridge Magnet — Matte Single",
        brand: "Prisbo Creations",
        description: "A single {{finish}} {{shape}} fridge magnet. {{pack}}. Customised with {{custom}}.",
        mrp: 199,
        price: 99,
        imageKey: "flexmagnet",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 500 }],
        specValues: { shape: "Heart", finish: "Matte", pack: "Single", custom: "Couple photo" },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catDecor._id,
    name: "Polaroid-Style Prints",
    displayOrder: 2,
    fields: [
      {
        key: "print_size",
        label: "Print size",
        type: "select",
        options: ["Classic 7.6×10.2cm", "Instax mini 5.4×8.6cm", "Square 6.2×6.2cm"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "pack",
        label: "Pack",
        type: "select",
        options: ["Set of 10", "Set of 20", "Set of 30"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "border",
        label: "Border colour",
        type: "select",
        options: ["White classic", "Black", "Pastel pink", "Custom colour"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "paper_finish",
        label: "Paper finish",
        type: "select",
        options: ["Glossy", "Matte", "Luster"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "packaging",
        label: "Packaging box",
        type: "select",
        options: ["Plain kraft box", "Custom printed box", "Kraft envelope"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Polaroid Mini Print Set — Classic 7.6×10.2cm Set of 20 White Border",
        brand: "Prisbo Creations",
        description:
          "{{pack}} of {{print_size}} prints with {{border}} borders on {{paper_finish}} paper. Packed in a {{packaging}}. Customised with {{custom}}.",
        mrp: 799,
        price: 499,
        imageKey: "polaroid",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          print_size: "Classic 7.6×10.2cm",
          pack: "Set of 20",
          border: "White classic",
          paper_finish: "Glossy",
          packaging: "Plain kraft box",
          custom: "Your photos",
        },
      },
      {
        name: "Instax Mini Photo Print Set of 30 — Pastel Pink Border Gift Box",
        brand: "Prisbo Creations",
        description:
          "{{pack}} of {{print_size}} prints, {{border}} border, {{paper_finish}} finish. Comes in a {{packaging}}.",
        mrp: 1099,
        price: 699,
        imageKey: "polaroid",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFC0CB", skuSuffix: "DEF", stock: 120 }],
        specValues: {
          print_size: "Instax mini 5.4×8.6cm",
          pack: "Set of 30",
          border: "Pastel pink",
          paper_finish: "Matte",
          packaging: "Custom printed box",
          custom: "Your photos + captions",
        },
      },
      {
        name: "Square Polaroid Prints — Black Border Set of 10",
        brand: "Prisbo Creations",
        description:
          "Set of {{pack}} {{print_size}} prints. {{border}} border. {{paper_finish}} finish. In a {{packaging}}.",
        mrp: 499,
        price: 299,
        imageKey: "polaroid",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#1A1A1A", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          print_size: "Square 6.2×6.2cm",
          pack: "Set of 10",
          border: "Black",
          paper_finish: "Luster",
          packaging: "Kraft envelope",
          custom: "Your photos",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catDecor._id,
    name: "Customised Coasters",
    displayOrder: 3,
    fields: [
      {
        key: "material",
        label: "Material",
        type: "select",
        options: ["Cork", "MDF wood", "Acrylic", "Ceramic", "Slate"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["Circle", "Square", "Hexagon"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "finish",
        label: "Finish",
        type: "select",
        options: ["Natural cork", "UV print", "Epoxy coated", "Engraved"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "set",
        label: "Set",
        type: "select",
        options: ["Single", "Set of 4", "Set of 6"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "occasion",
        label: "Occasion",
        type: "select",
        options: ["Wedding favour", "Housewarming", "Corporate", "Home use"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Personalised Cork Coasters — Set of 4 Round Engraved Monogram",
        brand: "Prisbo Creations",
        description:
          "{{set}} of {{material}} {{shape}} coasters with {{finish}} treatment. Perfect for {{occasion}}. Customised with {{custom}}.",
        mrp: 799,
        price: 499,
        imageKey: "coaster",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#C4A265", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          material: "Cork",
          shape: "Circle",
          finish: "Engraved",
          set: "Set of 4",
          occasion: "Home use",
          custom: "Monogram or family name",
        },
      },
      {
        name: "Wedding Favour Coasters — MDF Set of 6 UV Printed Custom",
        brand: "Prisbo Creations",
        description:
          "{{set}} of {{material}} {{shape}} coasters with {{finish}}. Perfect {{occasion}} gift. Customised with {{custom}}.",
        mrp: 1199,
        price: 749,
        imageKey: "coaster",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#D4A07A", skuSuffix: "DEF", stock: 100 }],
        specValues: {
          material: "MDF wood",
          shape: "Circle",
          finish: "UV print",
          set: "Set of 6",
          occasion: "Wedding favour",
          custom: "Couple names + wedding date + photo",
        },
      },
      {
        name: "Acrylic Epoxy Coasters — Set of 4 Hexagon Custom Photo",
        brand: "Prisbo Creations",
        description:
          "Premium {{material}} {{shape}} coasters with {{finish}} finish. {{set}}. For {{occasion}}. Customised with {{custom}}.",
        mrp: 999,
        price: 649,
        imageKey: "coaster",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#E8EDF5", skuSuffix: "DEF", stock: 80 }],
        specValues: {
          material: "Acrylic",
          shape: "Hexagon",
          finish: "Epoxy coated",
          set: "Set of 4",
          occasion: "Housewarming",
          custom: "Family photo or illustration",
        },
      },
    ],
  });

  console.log("✓ Home Decor & Lifestyle done");

  await seedSubcategory({
    categoryId: catTextile._id,
    name: "Personalised Cushions",
    displayOrder: 1,
    fields: [
      {
        key: "type",
        label: "Cushion type",
        type: "select",
        options: ["Standard photo cushion", "Magic reveal (sequin flip)", "Heart shaped"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["12×12 inch (30×30cm)", "16×16 inch (40×40cm)", "12×18 inch (30×46cm)"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "cover",
        label: "Cover material",
        type: "select",
        options: ["Satin", "Polyester canvas", "Velvet", "Linen blend"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "fill",
        label: "Fill",
        type: "select",
        options: ["With PP fibre insert", "Cover only (no fill)"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
    ],
    products: [
      {
        name: "Personalised Photo Cushion — Satin 16×16 inch with Fill",
        brand: "Prisbo Creations",
        description: "A beautiful {{type}} {{cover}} cushion, {{size}}. {{fill}}. Fully customised with {{custom}}.",
        mrp: 999,
        price: 599,
        imageKey: "cushion",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Default", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 100 }],
        specValues: {
          type: "Standard photo cushion",
          size: "16×16 inch (40×40cm)",
          cover: "Satin",
          fill: "With PP fibre insert",
          custom: "Family photo + names",
        },
      },
      {
        name: "Magic Sequin Flip Cushion — Custom Photo Reveal 16×16 inch",
        brand: "Prisbo Creations",
        description:
          "Magical {{type}} {{cover}} cushion, {{size}}. Swipe to reveal your {{custom}}. {{fill}}.",
        mrp: 1299,
        price: 849,
        imageKey: "cushion",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Silver", hexCode: "#C0C0C0", skuSuffix: "SLV", stock: 60 },
          { displayName: "Gold", hexCode: "#FFD700", skuSuffix: "GLD", stock: 60 },
          { displayName: "Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 60 },
        ],
        specValues: {
          type: "Magic reveal (sequin flip)",
          size: "16×16 inch (40×40cm)",
          cover: "Polyester canvas",
          fill: "With PP fibre insert",
          custom: "Photo hidden beneath sequins",
        },
      },
      {
        name: "Heart Shaped Photo Cushion — Velvet 12×18 inch Personalised",
        brand: "Prisbo Creations",
        description: "A romantic {{type}} in {{cover}}, {{size}}. {{fill}}. Customised with {{custom}}.",
        mrp: 1099,
        price: 699,
        imageKey: "cushion",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Deep Red", hexCode: "#8B0000", skuSuffix: "RED", stock: 50 },
          { displayName: "Dusty Rose", hexCode: "#C17A8A", skuSuffix: "RSE", stock: 50 },
          { displayName: "Ivory", hexCode: "#FFFFF0", skuSuffix: "IVR", stock: 50 },
        ],
        specValues: {
          type: "Heart shaped",
          size: "12×18 inch (30×46cm)",
          cover: "Velvet",
          fill: "With PP fibre insert",
          custom: "Couple photo + names",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catTextile._id,
    name: "Custom Mugs & Sippers",
    displayOrder: 2,
    fields: [
      {
        key: "type",
        label: "Mug type",
        type: "select",
        options: [
          "Ceramic mug (standard)",
          "Magic colour change mug",
          "Travel sipper (steel)",
          "Glass mug",
          "Conical mug",
        ],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "capacity",
        label: "Capacity",
        type: "select",
        options: ["325ml", "450ml", "500ml (sipper)"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "print",
        label: "Print coverage",
        type: "select",
        options: ["Full wrap 360°", "Half wrap", "Patch/logo only"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "colour",
        label: "Base colour",
        type: "select",
        options: ["White base", "Black base (magic)", "Custom body colour"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "box",
        label: "Packaging",
        type: "select",
        options: ["Plain white box", "Custom gift box"],
        isHighlight: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Custom Photo Ceramic Mug — Full Wrap 325ml White Base",
        brand: "Prisbo Creations",
        description:
          "A {{type}} in {{colour}}, {{capacity}}, with {{print}} sublimation print. Comes in a {{box}}. Customised with {{custom}}.",
        mrp: 599,
        price: 299,
        imageKey: "mug",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "White", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 200 }],
        specValues: {
          type: "Ceramic mug (standard)",
          capacity: "325ml",
          print: "Full wrap 360°",
          colour: "White base",
          box: "Plain white box",
          custom: "Photo + name or quote",
        },
      },
      {
        name: "Magic Colour Change Mug — Custom Photo Reveal 325ml",
        brand: "Prisbo Creations",
        description:
          "{{type}} in {{colour}}, {{capacity}}. Add hot liquid to reveal {{custom}}. {{print}}. Packed in {{box}}.",
        mrp: 799,
        price: 449,
        imageKey: "mug",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "Black", hexCode: "#1A1A1A", skuSuffix: "DEF", stock: 150 }],
        specValues: {
          type: "Magic colour change mug",
          capacity: "325ml",
          print: "Full wrap 360°",
          colour: "Black base (magic)",
          box: "Custom gift box",
          custom: "Hidden photo or message",
        },
      },
      {
        name: "Personalised Steel Travel Sipper — 500ml Full Wrap Custom",
        brand: "Prisbo Creations",
        description:
          "A {{capacity}} {{type}} with {{print}} print. Customised with {{custom}}. Comes in a {{box}}.",
        mrp: 899,
        price: 549,
        imageKey: "mug",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Silver", hexCode: "#C0C0C0", skuSuffix: "SLV", stock: 80 },
          { displayName: "Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 80 },
          { displayName: "White", hexCode: "#FFFFFF", skuSuffix: "WHT", stock: 80 },
        ],
        specValues: {
          type: "Travel sipper (steel)",
          capacity: "500ml (sipper)",
          print: "Full wrap 360°",
          colour: "Custom body colour",
          box: "Custom gift box",
          custom: "Name + photo or design",
        },
      },
      {
        name: "Custom Conical Mug — 450ml Half Wrap Photo Print",
        brand: "Prisbo Creations",
        description:
          "Classic {{type}} in {{colour}}, {{capacity}}, {{print}} sublimation. Packed in {{box}}. Customised with {{custom}}.",
        mrp: 699,
        price: 349,
        imageKey: "mug",
        hasColourVariants: false,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [{ displayName: "White", hexCode: "#FFFFFF", skuSuffix: "DEF", stock: 120 }],
        specValues: {
          type: "Conical mug",
          capacity: "450ml",
          print: "Half wrap",
          colour: "White base",
          box: "Plain white box",
          custom: "Photo + name",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catTextile._id,
    name: "Branded Caps",
    displayOrder: 3,
    fields: [
      {
        key: "cap_style",
        label: "Cap style",
        type: "select",
        options: ["Snapback 6-panel", "5-panel camp cap", "Dad hat (unstructured)", "Trucker mesh"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "print_method",
        label: "Print method",
        type: "select",
        options: ["Embroidery", "DTF transfer", "Screen print", "Sublimation patch"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "placement",
        label: "Placement",
        type: "select",
        options: ["Front centre", "Side logo", "Back text"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "closure",
        label: "Closure",
        type: "select",
        options: ["Snapback", "Velcro", "Fitted"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "min_qty",
        label: "Minimum qty",
        type: "select",
        options: ["12 pcs", "24 pcs", "50 pcs"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Custom Embroidered Cap — Snapback 6-Panel Team or Brand Logo",
        brand: "Prisbo Creations",
        description:
          "Premium {{cap_style}} with {{print_method}} on {{placement}}. {{closure}} closure. Minimum {{min_qty}}. Customised with {{custom}}.",
        mrp: 699,
        price: 449,
        imageKey: "cap",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 120 },
          { displayName: "Navy", hexCode: "#003153", skuSuffix: "NVY", stock: 120 },
          { displayName: "White", hexCode: "#FFFFFF", skuSuffix: "WHT", stock: 120 },
          { displayName: "Red", hexCode: "#CC0000", skuSuffix: "RED", stock: 80 },
        ],
        specValues: {
          cap_style: "Snapback 6-panel",
          print_method: "Embroidery",
          placement: "Front centre",
          closure: "Snapback",
          min_qty: "12 pcs",
          custom: "Team name or company logo",
        },
      },
      {
        name: "Trucker Mesh Cap — DTF Print Custom Sports Team Branded",
        brand: "Prisbo Creations",
        description:
          "Breathable {{cap_style}} with {{print_method}} on {{placement}}. {{closure}} closure. Minimum {{min_qty}}.",
        mrp: 599,
        price: 349,
        imageKey: "cap",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: true,
        variants: [
          { displayName: "Black/Black", hexCode: "#1A1A1A", skuSuffix: "BLK", stock: 100 },
          { displayName: "Navy/White", hexCode: "#003153", skuSuffix: "NVY", stock: 100 },
          { displayName: "White/Black", hexCode: "#FFFFFF", skuSuffix: "WHT", stock: 100 },
        ],
        specValues: {
          cap_style: "Trucker mesh",
          print_method: "DTF transfer",
          placement: "Front centre",
          closure: "Snapback",
          min_qty: "12 pcs",
          custom: "Team logo or name",
        },
      },
    ],
  });

  await seedSubcategory({
    categoryId: catTextile._id,
    name: "Branded T-Shirts",
    displayOrder: 4,
    fields: [
      {
        key: "neck",
        label: "Neck style",
        type: "select",
        options: ["Round neck", "Polo collar", "V-neck"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 0,
      },
      {
        key: "fit",
        label: "Fit",
        type: "select",
        options: ["Regular", "Slim", "Oversized"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 1,
      },
      {
        key: "fabric",
        label: "Fabric",
        type: "select",
        options: ["100% polyester (sublimation)", "Cotton blend (DTF/screen)"],
        isHighlight: true,
        isRequired: true,
        displayOrder: 2,
      },
      {
        key: "print",
        label: "Print method",
        type: "select",
        options: ["Sublimation (full front)", "DTF transfer", "Screen print"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 3,
      },
      {
        key: "min_qty",
        label: "Minimum qty",
        type: "select",
        options: ["12 pcs", "24 pcs", "50 pcs"],
        isHighlight: false,
        isRequired: true,
        displayOrder: 4,
      },
      {
        key: "custom",
        label: "Customisation",
        type: "text",
        options: [],
        isHighlight: false,
        isRequired: true,
        displayOrder: 5,
      },
    ],
    products: [
      {
        name: "Custom Round Neck T-Shirt — Sublimation Full Front Team Print",
        brand: "Prisbo Creations",
        description:
          "{{fit}} fit {{neck}} {{fabric}} t-shirt with {{print}} printing. Minimum {{min_qty}}. Customised with {{custom}}.",
        mrp: 699,
        price: 399,
        imageKey: "tshirt",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: false,
        variants: [
          {
            displayName: "White",
            hexCode: "#FFFFFF",
            skuSuffix: "WHT",
            stock: 0,
            sizes: [
              { size: "XS", stock: 20 },
              { size: "S", stock: 30 },
              { size: "M", stock: 40 },
              { size: "L", stock: 40 },
              { size: "XL", stock: 30 },
              { size: "XXL", stock: 20 },
              { size: "3XL", stock: 10 },
            ],
          },
          {
            displayName: "Black",
            hexCode: "#1A1A1A",
            skuSuffix: "BLK",
            stock: 0,
            sizes: [
              { size: "XS", stock: 15 },
              { size: "S", stock: 25 },
              { size: "M", stock: 35 },
              { size: "L", stock: 35 },
              { size: "XL", stock: 25 },
              { size: "XXL", stock: 15 },
              { size: "3XL", stock: 8 },
            ],
          },
          {
            displayName: "Navy Blue",
            hexCode: "#003153",
            skuSuffix: "NVY",
            stock: 0,
            sizes: [
              { size: "XS", stock: 10 },
              { size: "S", stock: 20 },
              { size: "M", stock: 30 },
              { size: "L", stock: 30 },
              { size: "XL", stock: 20 },
              { size: "XXL", stock: 10 },
              { size: "3XL", stock: 5 },
            ],
          },
        ],
        specValues: {
          neck: "Round neck",
          fit: "Regular",
          fabric: "100% polyester (sublimation)",
          print: "Sublimation (full front)",
          min_qty: "12 pcs",
          custom: "Team logo + name + number",
        },
      },
      {
        name: "Polo Collar Branded T-Shirt — Cotton DTF Print Corporate",
        brand: "Prisbo Creations",
        description:
          "Professional {{fit}} fit {{neck}} {{fabric}} t-shirt with {{print}} print. Minimum {{min_qty}}. Customised with {{custom}}.",
        mrp: 899,
        price: 549,
        imageKey: "tshirt",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: false,
        variants: [
          {
            displayName: "White",
            hexCode: "#FFFFFF",
            skuSuffix: "WHT",
            stock: 0,
            sizes: [
              { size: "S", stock: 20 },
              { size: "M", stock: 30 },
              { size: "L", stock: 30 },
              { size: "XL", stock: 20 },
              { size: "XXL", stock: 10 },
            ],
          },
          {
            displayName: "Sky Blue",
            hexCode: "#87CEEB",
            skuSuffix: "SKY",
            stock: 0,
            sizes: [
              { size: "S", stock: 15 },
              { size: "M", stock: 25 },
              { size: "L", stock: 25 },
              { size: "XL", stock: 15 },
              { size: "XXL", stock: 8 },
            ],
          },
          {
            displayName: "Dark Grey",
            hexCode: "#555555",
            skuSuffix: "GRY",
            stock: 0,
            sizes: [
              { size: "S", stock: 12 },
              { size: "M", stock: 20 },
              { size: "L", stock: 20 },
              { size: "XL", stock: 12 },
              { size: "XXL", stock: 6 },
            ],
          },
        ],
        specValues: {
          neck: "Polo collar",
          fit: "Regular",
          fabric: "Cotton blend (DTF/screen)",
          print: "DTF transfer",
          min_qty: "12 pcs",
          custom: "Company logo + employee name",
        },
      },
      {
        name: "Oversized Graphic T-Shirt — DTF Full Front Custom Print",
        brand: "Prisbo Creations",
        description:
          "{{fit}} fit {{neck}} {{fabric}} tee with {{print}} print. Minimum {{min_qty}}. Customised with {{custom}}.",
        mrp: 799,
        price: 499,
        imageKey: "tshirt",
        hasColourVariants: true,
        hasSizePricing: false,
        sizesNotApplicable: false,
        variants: [
          {
            displayName: "White",
            hexCode: "#FFFFFF",
            skuSuffix: "WHT",
            stock: 0,
            sizes: [
              { size: "S", stock: 15 },
              { size: "M", stock: 25 },
              { size: "L", stock: 30 },
              { size: "XL", stock: 25 },
              { size: "XXL", stock: 15 },
              { size: "3XL", stock: 8 },
            ],
          },
          {
            displayName: "Sand",
            hexCode: "#C4A265",
            skuSuffix: "SND",
            stock: 0,
            sizes: [
              { size: "S", stock: 12 },
              { size: "M", stock: 20 },
              { size: "L", stock: 25 },
              { size: "XL", stock: 20 },
              { size: "XXL", stock: 12 },
              { size: "3XL", stock: 6 },
            ],
          },
          {
            displayName: "Dusty Pink",
            hexCode: "#C17A8A",
            skuSuffix: "PNK",
            stock: 0,
            sizes: [
              { size: "S", stock: 10 },
              { size: "M", stock: 18 },
              { size: "L", stock: 22 },
              { size: "XL", stock: 18 },
              { size: "XXL", stock: 10 },
              { size: "3XL", stock: 5 },
            ],
          },
        ],
        specValues: {
          neck: "Round neck",
          fit: "Oversized",
          fabric: "Cotton blend (DTF/screen)",
          print: "DTF transfer",
          min_qty: "12 pcs",
          custom: "Custom graphic artwork + text",
        },
      },
    ],
  });

  console.log("✓ Textiles & Apparel done");
}
